---
deployment:
  tasks:
    - export DEPLOYPATH=/home/umfvztzh/public_html
    # - /bin/cp -rf images $DEPLOYPATH
    # - /bin/cp -rf content $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env $DEPLOYPATH/.env